/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    books: Book;
    categories: Category;
    series: Series;
    lessons: Lesson;
    articles: Article;
    pages: Page;
    announcements: Announcement;
    events: Event;
    carts: Cart;
    orders: Order;
    paymentEvents: PaymentEvent;
    mockPaymentSessions: MockPaymentSession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    paymentEvents: PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    mockPaymentSessions: MockPaymentSessionsSelect<false> | MockPaymentSessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('he' | 'en' | 'fr') | ('he' | 'en' | 'fr')[];
  globals: {
    schedule: Schedule;
    shippingSettings: ShippingSetting;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    shippingSettings: ShippingSettingsSelect<false> | ShippingSettingsSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'he' | 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  slug: string;
  /**
   * כתובת ה-URL הציבורית והיחידה של הספר, זהה בכל שפה. נוצרת אוטומטית מהכותרת; שינוי ידני אפשרי אך חייב להישאר ייחודי בכל הקטלוג.
   */
  urlSlug: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bookLanguage: 'he' | 'fr' | 'en' | 'he-fr' | 'aramaic-fr' | 'unknown';
  category?: (number | null) | Category;
  prices: {
    currency: 'ILS' | 'EUR' | 'USD';
    /**
     * Minor units (agorot/cents) as an integer — never a float.
     */
    amount: number;
    id?: string | null;
  }[];
  cover?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  inStock?: boolean | null;
  shippingUnits: number;
  /**
   * השאירו ריק אם תאריך הפרסום האמיתי אינו ידוע.
   */
  publishedAt?: string | null;
  /**
   * e.g. תשפ״ו
   */
  hebrewYear?: string | null;
  isbn?: string | null;
  relatedSeries?: (number | Series)[] | null;
  legacyUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  needsReview?: boolean | null;
  reviewReasons?:
    | (
        | 'missing-description'
        | 'price-mismatch'
        | 'absent-from-hebrew'
        | 'ambiguous-match'
        | 'language-uncertain'
        | 'zero-price'
      )[]
    | null;
  /**
   * For example, an ambiguous-match counterpart's title.
   */
  reviewNote?: string | null;
  importKey?: string | null;
  importedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  language: 'he' | 'fr';
  relatedBook?: (number | null) | Book;
  youtubePlaylistId?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  series: number | Series;
  youtubeId?: string | null;
  /**
   * Object-storage key for the audio file, not the file itself.
   */
  audioKey?: string | null;
  recordedAt?: string | null;
  language?: ('he' | 'fr') | null;
  durationSeconds?: number | null;
  /**
   * Timestamp from the sync source, used to make re-syncing idempotent.
   */
  sourceUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'parsha' | 'holiday' | 'general';
  parsha?:
    | (
        | 'בראשית'
        | 'נח'
        | 'לך לך'
        | 'וירא'
        | 'חיי שרה'
        | 'תולדות'
        | 'ויצא'
        | 'וישלח'
        | 'וישב'
        | 'מקץ'
        | 'ויגש'
        | 'ויחי'
        | 'שמות'
        | 'וארא'
        | 'בא'
        | 'בשלח'
        | 'יתרו'
        | 'משפטים'
        | 'תרומה'
        | 'תצוה'
        | 'כי תשא'
        | 'ויקהל'
        | 'פקודי'
        | 'ויקרא'
        | 'צו'
        | 'שמיני'
        | 'תזריע'
        | 'מצורע'
        | 'אחרי מות'
        | 'קדושים'
        | 'אמור'
        | 'בהר'
        | 'בחקתי'
        | 'במדבר'
        | 'נשא'
        | 'בהעלתך'
        | 'שלח'
        | 'קרח'
        | 'חקת'
        | 'בלק'
        | 'פינחס'
        | 'מטות'
        | 'מסעי'
        | 'דברים'
        | 'ואתחנן'
        | 'עקב'
        | 'ראה'
        | 'שופטים'
        | 'כי תצא'
        | 'כי תבוא'
        | 'נצבים'
        | 'וילך'
        | 'האזינו'
        | 'וזאת הברכה'
      )
    | null;
  holiday?:
    ('ימים נוראים' | 'סוכות' | 'חנוכה' | 'פורים' | 'פסח' | 'שבועות' | 'ט״ו בשבט' | 'י״ז בתמוז ותשעה באב') | null;
  publishedAt?: string | null;
  legacyUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  legacyUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  location?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  sessionId: string;
  items?:
    | {
        book: number | Book;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: number | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'cancelled';
  fulfilmentStatus?: ('new' | 'packed' | 'posted' | 'collected') | null;
  customer: {
    name: string;
    email: string;
    phone: string;
    address?: {
      line1?: string | null;
      line2?: string | null;
      city?: string | null;
      postalCode?: string | null;
    };
  };
  lines: {
    book?: (number | null) | Book;
    title: string;
    /**
     * Minor units (agorot/cents) as an integer.
     */
    unitPrice: number;
    currency: 'ILS' | 'EUR' | 'USD';
    quantity: number;
    shippingUnits: number;
    id?: string | null;
  }[];
  currency: 'ILS' | 'EUR' | 'USD';
  /**
   * Minor units (agorot/cents) as an integer.
   */
  subtotal: number;
  /**
   * Minor units (agorot/cents) as an integer.
   */
  shippingCost: number;
  /**
   * Minor units (agorot/cents) as an integer.
   */
  total: number;
  formattedTotal?: string | null;
  shippingZone: string;
  destinationCountry: string;
  isPickup?: boolean | null;
  locale: 'he' | 'en' | 'fr';
  provider: string;
  providerRef?: string | null;
  paidAt?: string | null;
  publicToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentEvents".
 */
export interface PaymentEvent {
  id: number;
  providerEventId: string;
  provider: string;
  order: number | Order;
  status: 'paid' | 'failed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mockPaymentSessions".
 */
export interface MockPaymentSession {
  id: number;
  providerRef: string;
  orderNumber: number;
  currency: 'ILS' | 'EUR' | 'USD';
  total: number;
  locale: 'he' | 'en' | 'fr';
  returnUrl: string;
  decision: 'awaiting' | 'paid' | 'declined' | 'cancelled';
  providerEventId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'paymentEvents';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'mockPaymentSessions';
        value: number | MockPaymentSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  urlSlug?: T;
  subtitle?: T;
  description?: T;
  bookLanguage?: T;
  category?: T;
  prices?:
    | T
    | {
        currency?: T;
        amount?: T;
        id?: T;
      };
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  inStock?: T;
  shippingUnits?: T;
  publishedAt?: T;
  hebrewYear?: T;
  isbn?: T;
  relatedSeries?: T;
  legacyUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  needsReview?: T;
  reviewReasons?: T;
  reviewNote?: T;
  importKey?: T;
  importedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  language?: T;
  relatedBook?: T;
  youtubePlaylistId?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  series?: T;
  youtubeId?: T;
  audioKey?: T;
  recordedAt?: T;
  language?: T;
  durationSeconds?: T;
  sourceUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  type?: T;
  parsha?: T;
  holiday?: T;
  publishedAt?: T;
  legacyUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  slug?: T;
  legacyUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  sessionId?: T;
  items?:
    | T
    | {
        book?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  paymentStatus?: T;
  fulfilmentStatus?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
              city?: T;
              postalCode?: T;
            };
      };
  lines?:
    | T
    | {
        book?: T;
        title?: T;
        unitPrice?: T;
        currency?: T;
        quantity?: T;
        shippingUnits?: T;
        id?: T;
      };
  currency?: T;
  subtotal?: T;
  shippingCost?: T;
  total?: T;
  formattedTotal?: T;
  shippingZone?: T;
  destinationCountry?: T;
  isPickup?: T;
  locale?: T;
  provider?: T;
  providerRef?: T;
  paidAt?: T;
  publicToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentEvents_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  providerEventId?: T;
  provider?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mockPaymentSessions_select".
 */
export interface MockPaymentSessionsSelect<T extends boolean = true> {
  providerRef?: T;
  orderNumber?: T;
  currency?: T;
  total?: T;
  locale?: T;
  returnUrl?: T;
  decision?: T;
  providerEventId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  shiurim?:
    | {
        title: string;
        /**
         * e.g. א׳–ה׳
         */
        days: string;
        /**
         * Free text, not a time field — "בין מנחה לערבית" is a valid value.
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  prayers?:
    | {
        name: string;
        /**
         * Free text, not a time field — "נץ החמה" is a valid value.
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingSettings".
 */
export interface ShippingSetting {
  id: number;
  zones: {
    /**
     * e.g. ישראל, אירופה, שאר העולם
     */
    name: string;
    /**
     * ISO country codes.
     */
    countries: string[];
    currency: 'ILS' | 'EUR' | 'USD';
    tiers: {
      minUnits: number;
      /**
       * Minor units (agorot/cents) as an integer — never a float.
       */
      amount: number;
      id?: string | null;
    }[];
    /**
     * Free shipping at or above this many units. Leave blank for no free tier.
     */
    freeAboveUnits?: number | null;
    allowPickup?: boolean | null;
    /**
     * The zone used when a destination matches no other zone. Flag exactly one.
     */
    isDefault?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The currency shown by default for each locale.
   */
  currencyByLocale?:
    | {
        locale: 'he' | 'en' | 'fr';
        currency: 'ILS' | 'EUR' | 'USD';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  shiurim?:
    | T
    | {
        title?: T;
        days?: T;
        time?: T;
        id?: T;
      };
  prayers?:
    | T
    | {
        name?: T;
        time?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingSettings_select".
 */
export interface ShippingSettingsSelect<T extends boolean = true> {
  zones?:
    | T
    | {
        name?: T;
        countries?: T;
        currency?: T;
        tiers?:
          | T
          | {
              minUnits?: T;
              amount?: T;
              id?: T;
            };
        freeAboveUnits?: T;
        allowPickup?: T;
        isDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  currencyByLocale?:
    | T
    | {
        locale?: T;
        currency?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}